### ISSUE TITLE
Don not create users if user exists

### ISSUE THREAD

**Issue by tbeckham** [shaon/riakcs-cluster#1]
We should check if the admin user specified already exists. If it does do not try to create a new user (this is what happens now and it will fail because her exists). This impacts performing upgrades with Calyptos. As a workaround I changed the admin name and email in the environment file to something unique, however this may not be the best solution.

Here is where you can see the admin-email and admin-name attributes that I changed. I just added "-update-10-06" to the original value
```
    topology:
      riakcs:
        access-key: ''
        admin-email: tony-1371-update-10-06@euca-qa.com
        admin-name: tony-1371-update-10-06
        endpoint: 10.111.1.60
        port: 80
        secret-key: ''
```
